import { StyleSheet } from "react-native";
import {
	responsiveWidth,
	responsiveHeight,
} from "react-native-responsive-dimensions";

const AdoptionLayout = StyleSheet.create({
	hill: {
		zIndex: 1,
		position: "absolute",
		// maxWidth: responsiveWidth(100),
		width: responsiveWidth(100),
		height: responsiveHeight(100),
	},

	runningDog22: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		top: 220,
		bottom: 0,
		left: -100,
		right: 0,
	},

	runningDog1: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 220,
		bottom: 0,
		left: 15,
		right: 20,
	},
	runningDog2: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		top: 250,
		bottom: 0,
		left: 5,
		right: 10,
	},
	runningDog3: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 300,
		bottom: 0,
		left: 30,
		right: 0,
	},
	runningDog4: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 250,
		bottom: 0,
		left: 50,
		right: 0,
	},
	runningDog5: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 290,
		bottom: 0,
		left: 100,
		right: 0,
	},
	runningDog6: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 280,
		bottom: 0,
		left: 0,
		right: 0,
	},
	runningDog7: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 270,
		bottom: 0,
		left: 80,
		right: 0,
	},
	runningDog8: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 270,
		bottom: 0,
		left: 40,
		right: 0,
	},
	runningDog9: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 250,
		bottom: 0,
		left: 100,
		right: 0,
	},
	runningDog10: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 300,
		bottom: 0,
		left: 80,
		right: 0,
	},
	runningDog11: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 230,
		bottom: 0,
		left: 80,
		right: 0,
	},
	cloud1: {
		zIndex: -2,
		width: 10,
		height: 10,
		position: "absolute",
		// justifyContent: "center",
		// alignItems: "center",
		top: 300,
		bottom: 0,
		left: 0,
		right: 0,
	},
	cloud2: {
		zIndex: -2,
		width: 100,
		height: 800,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 0,
		bottom: 0,
		left: 100,
		right: 0,
	},
	cloud3: {
		zIndex: -2,
		width: 100,
		height: 400,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 120,
		bottom: 0,
		left: 100,
		right: 0,
	},
	cloud4: {
		zIndex: -2,
		width: 100,
		height: 400,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 0,
		bottom: 0,
		left:100,
		right: 0,
	},
	cloud5: {
		zIndex: -2,
		width: 100,
		height: 500,
		position: "absolute",
		top: 150,
		bottom: 0,
		left: 0,
		right: 0,
	},
	cloud6: {
		zIndex: -2,
		width: 100,
		height: 100,
		position: "absolute",
		top: 50,
		bottom: 0,
		left: 80,
		right: 0,
	},
	cloud7: {
		zIndex: -3,
		width: 100,
		height: 700,
		position: "absolute",
		top: 120,
		bottom: 0,
		left: 100,
		right: 0,
	},
	cloud8: {
		zIndex: -4,
		width: 100,
		height: 600,
		position: "absolute",
		top: 100,
		bottom: 0,
		left: 30,
		right: 0,
	},
	cloud9: {
		zIndex: -2,
		width: 100,
		height: 700,
		position: "absolute",
		top: 150,
		bottom: 0,
		left: 0,
		right: 0,
	},
	cloud10: {
		zIndex: -2,
		width: 100,
		height: 500,
		position: "absolute",
		top: 50,
		bottom: 0,
		left: 0,
		right: 30,
	},
	cloud11: {
		zIndex: -2,
		width: 100,
		height: 500,
		position: "absolute",
		top: 200,
		bottom: 0,
		left: 80,
		right: 0,
	},
});

export default AdoptionLayout;
