import { StyleSheet } from "react-native";
import {
	responsiveWidth,
	responsiveHeight,
} from "react-native-responsive-dimensions";

const AdoptionLayout = StyleSheet.create({
	heaven: {
		zIndex: -5,
		position: "absolute",
		// maxWidth: responsiveWidth(100),
		width: responsiveWidth(100),
		height: responsiveHeight(100),
	},
	planet: {
		zIndex: -4,
		position: "absolute",
		top: responsiveHeight(40),
		left: 0,
		height: 400,
		width: 400,
	},
	heavencloud: {
		zIndex: -4,
		position: "absolute",
		top: responsiveHeight(30),
		left: "0%",
		height: responsiveHeight(60),
		width: responsiveHeight(50),
	},
	heavencloud2: {
		zIndex: -4,
		position: "absolute",
		top: responsiveHeight(50),
		left: "0%",
		height: responsiveHeight(50),
		width: responsiveHeight(100),
	},
	Dancingdog: {
		zIndex: -4,
		position: "absolute",
		top: "38%",
		left: "35%",
		height: responsiveHeight(15),
		width: responsiveHeight(20),
	},
	heavenground: {
		zIndex: -5,
		position: "absolute",
		top: responsiveHeight(15),
		left: responsiveWidth(-2),
		height: responsiveHeight(30),
		width: responsiveWidth(50),
	},

	hill: {
		zIndex: 1,
		position: "absolute",
		// maxWidth: responsiveWidth(100),
		width: responsiveWidth(100),
		height: responsiveHeight(100),
	},

	light: {
		zIndex: -5,
		position: "absolute",
		// maxWidth: responsiveWidth(100),
		top: responsiveHeight(-25),
	},

	cube: {
		zIndex: -3,
		position: "absolute",
		top: responsiveHeight(-30),
		left: responsiveWidth(0),
	},
	heavencloud4: {
		zIndex: -5,
		position: "absolute",
		top: responsiveHeight(22),
		left: responsiveWidth(50),
	},

	runningDog22: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		top: 220,
		bottom: 0,
		left: -100,
		right: 0,
	},

	runningDog1: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 220,
		bottom: 0,
		left: 15,
		right: 20,
	},
	runningDog2: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		top: 250,
		bottom: 0,
		left: 5,
		right: 10,
	},
	runningDog3: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 300,
		bottom: 0,
		left: 30,
		right: 0,
	},
	runningDog4: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 250,
		bottom: 0,
		left: 50,
		right: 0,
	},
	runningDog5: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 290,
		bottom: 0,
		left: 100,
		right: 0,
	},
	runningDog6: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 280,
		bottom: 0,
		left: 0,
		right: 0,
	},
	runningDog7: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 270,
		bottom: 0,
		left: 80,
		right: 0,
	},
	runningDog8: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 270,
		bottom: 0,
		left: 40,
		right: 0,
	},
	runningDog9: {
		zIndex: 3,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 250,
		bottom: 0,
		left: 100,
		right: 0,
	},
	runningDog10: {
		zIndex: 2,
		width: 100,
		height: 100,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 300,
		bottom: 0,
		left: 80,
		right: 0,
	},
	runningDog11: {
		zIndex: 2,
		width: 100,
		height: 1000,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 230,
		bottom: 0,
		left: 80,
		right: 0,
	},
	cloud1: {
		zIndex: -2,
		width: 100,
		height: 700,
		position: "absolute",
		// justifyContent: "center",
		// alignItems: "center",
		top: 300,
		bottom: 0,
		left: 0,
		right: 0,
	},
	cloud2: {
		zIndex: -2,
		width: 100,
		height: 800,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 0,
		bottom: 0,
		left: 100 - 80,
		right: 0,
	},
	cloud3: {
		zIndex: -2,
		width: 100,
		height: 700,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 120,
		bottom: 0,
		left: 150 - 80,
		right: 0,
	},
	cloud4: {
		zIndex: -2,
		width: 100,
		height: 700,
		position: "absolute",
		justifyContent: "center",
		alignItems: "center",
		top: 0,
		bottom: 0,
		left: 100 - 80,
		right: 0,
	},
	cloud5: {
		zIndex: -2,
		width: 100,
		height: 800,
		position: "absolute",
		top: responsiveHeight(0),
		bottom: 0,
		left: responsiveWidth(35),
		right: 0,
	},
	cloud6: {
		zIndex: -2,
		width: 100,
		height: 700,
		position: "absolute",
		top: responsiveHeight(20),
		bottom: 0,
		left: responsiveWidth(30),
		right: 0,
	},
	cloud7: {
		zIndex: -3,
		width: 100,
		height: 700,
		position: "absolute",
		top: responsiveHeight(20),
		bottom: 0,
		left: 100 - 80,
		right: 0,
	},
	cloud8: {
		zIndex: -4,
		width: 100,
		height: 600,
		position: "absolute",
		top: responsiveHeight(10),
		bottom: 0,
		left: responsiveWidth(0),
		right: 0,
	},
	cloud9: {
		zIndex: -2,
		width: 100,
		height: responsiveHeight(100),
		position: "absolute",
		top: responsiveHeight(10),
		bottom: 0,
		left: responsiveWidth(25),
		right: 0,
	},
	cloud10: {
		zIndex: -2,
		width: 100,
		height: 500,
		position: "absolute",
		top: 50,
		bottom: 0,
		left: responsiveWidth(16),
		right: 30,
	},
	cloud11: {
		zIndex: -2,
		position: "absolute",
		top: responsiveHeight(15),
		bottom: 0,
		left: responsiveWidth(20),
	},
	dog1of3: {
		zIndex: 5,
		position: "absolute",
		top: responsiveHeight(0),
		bottom: 0,
		left: responsiveWidth(0),
	},

	dog2of3: {
		zIndex: 5,
		position: "absolute",
		top: responsiveHeight(0),
		bottom: 0,
		left: responsiveWidth(0),
	},
});

export default AdoptionLayout;
